FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["OSDC.YPL.ModelCalibration.FromRheometer.Service/OSDC.YPL.ModelCalibration.FromRheometer.Service.csproj", "OSDC.YPL.ModelCalibration.FromRheometer.Service/"]
RUN dotnet restore "OSDC.YPL.ModelCalibration.FromRheometer.Service/OSDC.YPL.ModelCalibration.FromRheometer.Service.csproj"
COPY . .
WORKDIR "/src/OSDC.YPL.ModelCalibration.FromRheometer.Service"
RUN dotnet build "OSDC.YPL.ModelCalibration.FromRheometer.Service.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "OSDC.YPL.ModelCalibration.FromRheometer.Service.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "OSDC.YPL.ModelCalibration.FromRheometer.Service.dll"]